# -*- coding: utf-8 -*-
"""Métodos: Ejercicios sobre números

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u9TaQLMAf9jovzfjOARJH849oCXsa1I5
"""

# Punto 1

for numeros_naturales in range(1,11):
  print(numeros_naturales)

# Punto 2

n = 1
while n<11:
  print (n)
  n = n + 1

# Punto 3

print("ingrese el valor final para (N)")
a = int(input())
b=0
for i in range (1, a+1):
  print(i)
  b=b+i
print("my_result", b)

#otra forma

n = 10
suma = 0
for i in range(1, n+1):
  suma += i
  my_result = suma 
print(my_result)

# Punto 4

n = 0
i = 1
while (i<11):
  n = n + i
  i = i + 1
print("my_result", n)

# Punto 5

suma = 0
m = int(input('Numero inicial:'))
n = int(input('Numero final:'))
 
for i in range(m,n+1):
  if i % 2 == 0:
    suma += i
 
print("My_result",suma)

# Punto 6

numeros = []
numero = 0
while numero<100:
    numero+=1
    if numero%2 != 0:
        numeros.append(numero)
print(sum(numeros))

# Punto 7

def func_sum_even_odd(b):
  sum_odd = 0
  sum_even = 0
  i = 0
  if type(b)==int or type(b)==float:
    while i <= b:
      if i%2==0:
        sum_even += i
        i +=1
      else:
        sum_odd += i
        i +=1

  else:
    print("argument must be an integer or float")
  return sum_odd, sum_even

